// Builds src/brand/assets.ts from brand/ (icons, doodles, logo). Strips metadata so the bundle stays small.
// Run: node scripts/gen-brand.mjs
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const read = (p) => fs.readFileSync(path.join(root, p), "utf8").replace(/<metadata>[\s\S]*?<\/metadata>/g, "");
const inner = (s) => s.match(/<svg[^>]*>([\s\S]*)<\/svg>/)[1].trim();
const viewBox = (s) => s.match(/viewBox="([^"]+)"/)[1];

const icons = {};
for (const f of fs.readdirSync(path.join(root, "brand/icons")).sort()) {
  if (f.endsWith(".svg")) icons[f.slice(0, -4)] = inner(read(`brand/icons/${f}`));
}

const asset = (p) => {
  const s = read(p);
  return { viewBox: viewBox(s), body: inner(s) };
};

const mark = asset("brand/logo/bajetje-mark-on-dark.svg");
const scribble = read("brand/doodles/underline-scribble.svg");
const confetti = [...read("brand/doodles/confetti.svg").matchAll(/<g id="c\d+">([\s\S]*?)<\/g>/g)].map((m) => m[1]);
const underline = { viewBox: viewBox(scribble), paths: [...scribble.matchAll(/ d="([^"]+)"/g)].map((m) => m[1]) };
const out = `// Generated by scripts/gen-brand.mjs from brand/. Do not edit by hand.
export type Svg = { viewBox: string; body: string };

export const ICONS = ${JSON.stringify(icons, null, 0)} as const;

export const WELCOME_DOODLE: Svg = ${JSON.stringify(asset("brand/doodles/welcome-doodle.svg"))};
export const HEALTH_EMPTY: Svg = ${JSON.stringify(asset("brand/doodles/commitment-health-empty.svg"))};
/** Scribble underline (brand/generators/underline.js): [main swipe, return pass], drawn on one after the other. */
export const UNDERLINE = ${JSON.stringify(underline)};
/** Doodle confetti pieces (brand/generators/confetti.js), 16 x 16 each, coloured with currentColor. */
export const CONFETTI: string[] = ${JSON.stringify(confetti)};
export const NOTE_ARROW: Svg = ${JSON.stringify(asset("brand/doodles/note-arrow.svg"))};
/** Sketch B mark on dark. Its clipPath id is "d"; give each use its own id with markBody(). */
export const MARK: Svg = ${JSON.stringify(mark)};
`;
fs.writeFileSync(path.join(root, "src/brand/assets.ts"), out);
console.log("icons:", Object.keys(icons).length, "bytes:", out.length);
